Traceback (most recent call last):
  File "/Users/hannaziegler/opt/anaconda3/envs/jbook/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/hannaziegler/opt/anaconda3/envs/jbook/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/hannaziegler/opt/anaconda3/envs/jbook/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/hannaziegler/opt/anaconda3/envs/jbook/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/hannaziegler/opt/anaconda3/envs/jbook/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/hannaziegler/opt/anaconda3/envs/jbook/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/hannaziegler/opt/anaconda3/envs/jbook/lib/python3.7/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/hannaziegler/opt/anaconda3/envs/jbook/lib/python3.7/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#text
fig3_3_title='Wie vielen Infizierten steht in welchem Landkreisen aktuell kein Bett zur Verf√ºgung?'
fig3_3_description='''Derzeit k√∂nnen in Summe in '''+str(anzahl_landkreise)+''' Landkreisen '''+str(anzahl_infizierte)+''' Infizierte nicht station√§r behandelt werden.'''
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/g7/m5kf9xs14511y51_chx__fs80000gn/T/ipykernel_34371/227844224.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m#text[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mfig3_3_title[0m[0;34m=[0m[0;34m'Wie vielen Infizierten steht in welchem Landkreisen aktuell kein Bett zur Verf√ºgung?'[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mfig3_3_description[0m[0;34m=[0m[0;34m'''Derzeit k√∂nnen in Summe in '''[0m[0;34m+[0m[0mstr[0m[0;34m([0m[0manzahl_landkreise[0m[0;34m)[0m[0;34m+[0m[0;34m''' Landkreisen '''[0m[0;34m+[0m[0mstr[0m[0;34m([0m[0manzahl_infizierte[0m[0;34m)[0m[0;34m+[0m[0;34m''' Infizierte nicht station√§r behandelt werden.'''[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'anzahl_landkreise' is not defined
NameError: name 'anzahl_landkreise' is not defined

